export const site = {
  name: "Rajan Chaudhary",
  shortName: "Rajan",
  role: "Full-Stack Developer",
  title: "Rajan Chaudhary — Full-Stack Developer | JavaScript, React, Next.js, Node.js",
  description:
    "Rajan Chaudhary is a full-stack developer and B.Tech Computer Science graduate building scalable web applications with React, Next.js, TypeScript, Node.js, Express, MongoDB, PostgreSQL, Redis, and Docker.",
  url: "https://rajanchaudhary947.vercel.app",
  email: "chaudharyrajan947@gmail.com",
  phone: "+91 6391652500",
  github: "https://github.com/Rajan-chaudhary-947",
  linkedin: "https://linkedin.com/in/rajanchaudhary947",
  leetcode: "https://leetcode.com/u/chaudharyrajan947",
  code360: "https://www.naukri.com/code360/profile/RajanS947",
  resumeHref: "https://drive.google.com/file/d/1NdpOY_aOGPv-c3T47S5Q1iqlyTRD3VHI/view?usp=sharing",
  avatarSrc: "/assets/images/Rajan%20chaudhary.png",
  ogImage: "/assets/images/portfolio.png",
  keywords: [
    "Rajan Chaudhary",
    "Full Stack Developer",
    "React Developer",
    "Next.js Developer",
    "Node.js Developer",
    "JavaScript Developer",
    "TypeScript Developer",
    "MongoDB Developer",
    "PostgreSQL Developer",
    "MERN Stack Developer",
    "Full Stack Web Developer",
    "Web Developer",
    "React Developer",
    "Next.js Developer",
    "Frontend Developer",
    "Backend Developer",
    "REST API Developer",
    "Express.js Developer",
    "Docker Developer",
    "Freelance Full Stack Developer",
    "Freelance React Developer",
    "Freelance Next.js Developer",
    "Freelance JavaScript Developer",
    "Freelance Web Developer India",
    "Freelance Web Development Services",
    "Hire Full Stack Developer",
    "Hire React Developer",
    "Hire Next.js Developer",
    "Custom Web Application Developer",
    "Website Development Services India",
    "Remote Freelance Developer",
    "Software Engineer India",
    "Web Developer India",
    "Freelancer",
    "Freelance Web Developer",
  ],
} as const;

export const navigation = [
  { label: "Work", href: "/work" },
  { label: "Skills", href: "/skills" },
  { label: "Credentials", href: "/credentials" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
